version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: aftas000
    ports:
      - "3307:3306"

  spring-app:
    build:
      context: ./aftas
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aftas000?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  aftas-frontend:
    build:
      context: ./FrontAftas
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring-app
